#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="${TRAINMARK_COMPOSE_FILE:-$ROOT_DIR/infra/docker-compose.yml}"

POSTGRES_DB="${POSTGRES_DB:-trainmark_ai}"
POSTGRES_USER="${POSTGRES_USER:-trainmark}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-trainmark_dev}"
POSTGRES_PORT="${POSTGRES_PORT:-55432}"
RABBITMQ_HOST="${RABBITMQ_HOST:-localhost}"
RABBITMQ_PORT="${RABBITMQ_PORT:-5672}"
RABBITMQ_USERNAME="${RABBITMQ_USERNAME:-trainmark}"
RABBITMQ_PASSWORD="${RABBITMQ_PASSWORD:-trainmark_dev}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-http://localhost:9000}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-trainmark}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-trainmark_dev_password}"
MINIO_BUCKET="${MINIO_BUCKET:-trainmark-reports}"
TRAINMARK_JDBC_URL="${TRAINMARK_JDBC_URL:-jdbc:postgresql://localhost:$POSTGRES_PORT/$POSTGRES_DB}"
TRAINMARK_JDBC_USERNAME="${TRAINMARK_JDBC_USERNAME:-$POSTGRES_USER}"
TRAINMARK_JDBC_PASSWORD="${TRAINMARK_JDBC_PASSWORD:-$POSTGRES_PASSWORD}"

export POSTGRES_DB
export POSTGRES_USER
export POSTGRES_PASSWORD
export POSTGRES_PORT
export RABBITMQ_HOST
export RABBITMQ_PORT
export RABBITMQ_USERNAME
export RABBITMQ_PASSWORD
export MINIO_ENDPOINT
export MINIO_ACCESS_KEY
export MINIO_SECRET_KEY
export MINIO_BUCKET

if [[ "${TRAINMARK_SKIP_INFRA:-0}" != "1" ]]; then
  echo "[dev:mvp:jdbc] Starting local infrastructure"
  docker compose -f "$COMPOSE_FILE" up -d
else
  echo "[dev:mvp:jdbc] Skipping infrastructure startup"
fi

if [[ "${TRAINMARK_SKIP_DB_MIGRATIONS:-0}" != "1" ]]; then
  bash "$ROOT_DIR/scripts/apply-db-migrations.sh"
else
  echo "[dev:mvp:jdbc] Skipping database migration check"
fi

export TRAINMARK_AUTH_STORE="${TRAINMARK_AUTH_STORE:-jdbc}"
export TRAINMARK_AUTH_JDBC_URL="${TRAINMARK_AUTH_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_AUTH_JDBC_USERNAME="${TRAINMARK_AUTH_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_AUTH_JDBC_PASSWORD="${TRAINMARK_AUTH_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_USER_STORE="${TRAINMARK_USER_STORE:-jdbc}"
export TRAINMARK_USER_JDBC_URL="${TRAINMARK_USER_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_USER_JDBC_USERNAME="${TRAINMARK_USER_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_USER_JDBC_PASSWORD="${TRAINMARK_USER_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_COURSE_STORE="${TRAINMARK_COURSE_STORE:-jdbc}"
export TRAINMARK_COURSE_JDBC_URL="${TRAINMARK_COURSE_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_COURSE_JDBC_USERNAME="${TRAINMARK_COURSE_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_COURSE_JDBC_PASSWORD="${TRAINMARK_COURSE_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_FILE_STORE="${TRAINMARK_FILE_STORE:-jdbc}"
export TRAINMARK_FILE_JDBC_URL="${TRAINMARK_FILE_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_FILE_JDBC_USERNAME="${TRAINMARK_FILE_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_FILE_JDBC_PASSWORD="${TRAINMARK_FILE_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"
export UPLOAD_REQUIRE_OBJECT_CONTENT="${UPLOAD_REQUIRE_OBJECT_CONTENT:-true}"

export TRAINMARK_OCR_STORE="${TRAINMARK_OCR_STORE:-jdbc}"
export TRAINMARK_OCR_JDBC_URL="${TRAINMARK_OCR_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_OCR_JDBC_USERNAME="${TRAINMARK_OCR_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_OCR_JDBC_PASSWORD="${TRAINMARK_OCR_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_GRADING_RUBRIC_STORE="${TRAINMARK_GRADING_RUBRIC_STORE:-jdbc}"
export TRAINMARK_GRADING_EXPORT_STORE="${TRAINMARK_GRADING_EXPORT_STORE:-jdbc}"
export TRAINMARK_GRADING_PUBLICATION_AUDIT_STORE="${TRAINMARK_GRADING_PUBLICATION_AUDIT_STORE:-jdbc}"
export TRAINMARK_GRADING_APPEAL_STORE="${TRAINMARK_GRADING_APPEAL_STORE:-jdbc}"
export TRAINMARK_GRADING_JOB_STORE="${TRAINMARK_GRADING_JOB_STORE:-jdbc}"
export TRAINMARK_GRADING_RESULT_STORE="${TRAINMARK_GRADING_RESULT_STORE:-jdbc}"
export TRAINMARK_GRADING_JDBC_URL="${TRAINMARK_GRADING_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_GRADING_JDBC_USERNAME="${TRAINMARK_GRADING_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_GRADING_JDBC_PASSWORD="${TRAINMARK_GRADING_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_NOTIFICATION_STORE="${TRAINMARK_NOTIFICATION_STORE:-jdbc}"
export TRAINMARK_NOTIFICATION_JDBC_URL="${TRAINMARK_NOTIFICATION_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_NOTIFICATION_JDBC_USERNAME="${TRAINMARK_NOTIFICATION_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_NOTIFICATION_JDBC_PASSWORD="${TRAINMARK_NOTIFICATION_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_SIMILARITY_STORE="${TRAINMARK_SIMILARITY_STORE:-jdbc}"
export TRAINMARK_SIMILARITY_JDBC_URL="${TRAINMARK_SIMILARITY_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_SIMILARITY_JDBC_USERNAME="${TRAINMARK_SIMILARITY_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_SIMILARITY_JDBC_PASSWORD="${TRAINMARK_SIMILARITY_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_ANALYTICS_STORE="${TRAINMARK_ANALYTICS_STORE:-jdbc}"
export TRAINMARK_ANALYTICS_JDBC_URL="${TRAINMARK_ANALYTICS_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_ANALYTICS_JDBC_USERNAME="${TRAINMARK_ANALYTICS_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_ANALYTICS_JDBC_PASSWORD="${TRAINMARK_ANALYTICS_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

export TRAINMARK_ADMIN_STORE="${TRAINMARK_ADMIN_STORE:-jdbc}"
export TRAINMARK_ADMIN_JDBC_URL="${TRAINMARK_ADMIN_JDBC_URL:-$TRAINMARK_JDBC_URL}"
export TRAINMARK_ADMIN_JDBC_USERNAME="${TRAINMARK_ADMIN_JDBC_USERNAME:-$TRAINMARK_JDBC_USERNAME}"
export TRAINMARK_ADMIN_JDBC_PASSWORD="${TRAINMARK_ADMIN_JDBC_PASSWORD:-$TRAINMARK_JDBC_PASSWORD}"

echo "[dev:mvp:jdbc] JDBC URL: $TRAINMARK_JDBC_URL"
exec bash "$ROOT_DIR/scripts/dev-mvp.sh"
